**Python Basics Assingment** 

In [ ]:
print('I don\'t want to be an "artist". I want to be a "Data Scientist."')

I don't want to be an "artist". I want to be a "Data Scientist."


**Basic Data Types Assingment**

In [ ]:
money=1000
for i in range(7):
  money+=money*0.12
print(money)

2210.6814074060803


In [ ]:
print("When we buy bitcoin with 1000 USD at the beginning of the week, we would earn {} USD at the end of the week, with an average gain of 12\%.".format(money-1000))

When we buy bitcoin with 1000 USD at the beginning of the week, we would earn 1210.6814074060803 USD at the end of the week, with an average gain of 12\%.


In [ ]:
F=input('Enter the temperature in Fahrenheit: ')
C = (5/9) * (int(F) - 32)
print("Temperature (C) : {}".format(C))

Enter the temperature in Fahrenheit: 220
Temperature (C) : 104.44444444444444


In [ ]:
sum_of_nums=0
for i in range(3):
  nums=input()
  sum_of_nums+=int(nums)
print("The sum of digits in the number is",sum_of_nums)  

1
2
3
The sum of digits in the number is 6


In [ ]:
first=input("first side lenth")
second=input("second side lenth")
hypo=(int(first)**2+int(second)**2)**0.5
print("The length of the hypotenuse is ",hypo)

first side lenth3
second side lenth4
The length of the hypotenuse is  5.0


**Variables Assingment**

In [ ]:
x=1
y='1'
x is y

False

In [ ]:
y=int(y)
x is y

True

**Lists Assingment**

In [ ]:
my_list = [34, 56, 76, 45, 2, 12, 67, 98, 37, 54, 66]
sorted=my_list.sort()
print("the sum of the two lowest numbers:",my_list[0]+my_list[1])
print("the sum of the two highest numbers:",my_list[len(my_list)-1]+my_list[len(my_list)-2])

the sum of the two lowest numbers: 14
the sum of the two highest numbers: 174


In [ ]:
ry

In [ ]:
names = ["David", "Michael", "John", "James", "Greg", "Mark", "William", "Richard", "Thomas", "Steven", 
          "Mary", "Susan", "Maria", "Karen", "Lisa", "Linda", "Donna", "Patricia", "Debra", "Eric"]

scores = [99, 87, 78, 86, 68, 94, 76, 97, 56, 98, 76, 87, 79, 90, 73, 93, 82, 69, 97, 98]
name=input("Name of student that you wanted to learn score of him/her: ")
index=names.index(name)
print(scores[index])

Name of student that you wanted to learn score of him/her: David
99


In [ ]:
max_score=max(scores)
num_of_students=scores.count(max_score)
print(" maximum score is {} and {} student got maximum score".format(max_score,num_of_students))

 maximum score is 99 and 1 student got maximum score


In [ ]:
months = ['January', 'February','March', 'April', 'May','June', 'July', 'August','September', 'October', 'November','December']
days=['31','30','31','30','31','30','31','31','30','31','30','31']
total=[months,days]
total_1=[[months],[days]]
spring = ['March', 'April', 'May']
summer = ['June', 'July', 'August']
fall = ['September', 'October', 'November']
winter = ['December', 'January', 'February']



**Dictionary Assingment**

In [ ]:
Days={ 1:'Monday',
       2:'Tuesday',
       3:'Wednesday',
       4:'Thursday',
       5:'Friday',
       6:'Saturday',
       7:'Sunday'
}
for i in range(2):
  selected_day=input('Select value of day to delete')
  del Days[int(selected_day)]
print(Days)

Select value of day to delete1
Select value of day to delete2
{3: 'Wednesday', 4: 'Thursday', 5: 'Friday', 6: 'Saturday', 7: 'Sunday'}


In [ ]:
persons = {
            "John":{
                "age":25,
                "sex":"Male" 
                    },
           "Lisa":{
                "age":28,
                "sex":"Female" 
                    },
           "Linda":{
                "age":32,
                "sex":"Female"
                    },
           "Micheal":{
                "age":41,
                "sex":"Male" 
                    }
                
            
        }
persons['Micheal']['child'] = {
    'Karen':{"age":12,
              "sex":"Female"},
    'Greg':{"age":7,
              "sex":"Male"}

}
persons['Linda']['child'] = {
    'Susan':{"age":6,
              "sex":"Female"}

}
print(persons)

{'John': {'age': 25, 'sex': 'Male'}, 'Lisa': {'age': 28, 'sex': 'Female'}, 'Linda': {'age': 32, 'sex': 'Female', 'child': {'Susan': {'age': 6, 'sex': 'Female'}}}, 'Micheal': {'age': 41, 'sex': 'Male', 'child': {'Karen': {'age': 12, 'sex': 'Female'}, 'Greg': {'age': 7, 'sex': 'Male'}}}}


In [ ]:
print(persons['Micheal']['child'])

{'Karen': {'age': 12, 'sex': 'Female'}, 'Greg': {'age': 7, 'sex': 'Male'}}


**Tuple and Set Assingment**

In [ ]:
week=( 'Monday',
       'Tuesday',
       'Wednesday',
       'Thursday',
       'Friday',
       'Saturday',
       'Sunday'
)
fruits={'apple','mango','orange'}
new_fruits={ 'cherry', 'peach', 'apple', 'mango'}
print(new_fruits.difference(fruits))
print(new_fruits.intersection(fruits))

{'peach', 'cherry'}
{'apple', 'mango'}


**Conditional Statements Assingment**

In [ ]:
type=input("enter type of degree F for fahrenheit,C for celcius")
if type=='F':
  F=input("enter fahrenheit degree")
  C = (5/9) * (int(F) - 32)
  print("{} fahrenheit is {} celcius".format(F,C))
elif type=='C':
  C= F=input("enter celcius degree")
  F=int(C)*(9/5)+32
  print("{} celcius is {} fahrenheit".format(C,F))
  


enter type of degree F for fahrenheit,C for celciusF
enter fahrenheit degree220
220 fahrenheit is 104.44444444444444 celcius


In [ ]:
salary=input("enter your salary")
year=input("enter your year of service")
salary=float(salary)
year=int(year)
if year>5:
  salary=salary+salary*0.05
  print("Your bonus is ",salary)
else:
  print("Sorry you can not get bonus")



enter your salary5500
enter your year of service6
Your bonus is  5775.0


In [ ]:
ages=[]
for i in range(3):
  age=input("enter age ")
  ages.append(int(age))
print(ages)  
print("Oldest age ",max(ages))
print("Youngest age ",min(ages))  

enter age 2
enter age 52
enter age 12
[2, 52, 12]
Oldest age  52
Youngest age  2


In [ ]:
classes=input("enter number of classes held")
attent=input("enter number of classes attended")
attent=int(attent)
classes=int(classes)
if attent/classes >= 0.75:
  print("you can attent to exam")
else:
  print("you are not allowed to exam")

enter number of classes held10
enter number of classes attended7
you are not allowed to exam


In [ ]:
letter=input("enter a letter")
if letter=='a' or letter=='e' or letter=='i' or letter=='o' or letter=='u':
  print( "letter is a vowel.")
elif letter=='y':
  print(" y is sometimes a vowel and sometimes a consonant.")
else:
  print(" the letter is a consonant.")

enter a lettery
 y is sometimes a vowel and sometimes a consonant.


**Loops Assingments**

In [ ]:
num=input("enter a number ")
num=int(num)
for i in range(1,11):
  print("{} x {} = {}".format(num,i,num*i))


enter a number 6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


In [ ]:
odds=[]
evens=[]
nums=[]
for i in range (21):
  if i%2==0:
    i=i**3
    evens.append(i)
    nums.append(i)
  else:
    i=i**2
    odds.append(i) 
    nums.append(i)
print(odds)
print(evens)
print(nums)


[1, 9, 25, 49, 81, 121, 169, 225, 289, 361]
[0, 8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832, 8000]
[0, 1, 8, 9, 64, 25, 216, 49, 512, 81, 1000, 121, 1728, 169, 2744, 225, 4096, 289, 5832, 361, 8000]


In [ ]:
user_input=[]
user_input=input("enter input")

for i in range(len(user_input)-1,-1,-1):
  print(user_input[i],end='')
  

enter inputautomobile
elibomotua

In [ ]:
odds=[]
evens=[]

for i in range(1, 201):
  if i%2==0:
    evens.append(i)

  else:
    odds.append(i) 
print(odds)
print(evens)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


In [ ]:
def count(list,n):
  count=0  
  for i in range(len(list)):
    if list[i]==n:
      count+=1
  return count      

list1=[1,2,1,1]
count(list1,1)    

3

In [ ]:
def digit_sum(n):
  n=str(n)
  sum_of_digit=0
  for i in range(len(n)):
    n=int(n)
    digit=n%10
    sum_of_digit+=digit
    n=n-digit
    n//=10
  if sum_of_digit>9:
    n=sum_of_digit
    return digit_sum(n)
  else:
    return sum_of_digit 

  
  
digit_sum(27684)  

9

In [ ]:
def gcd(x, y):
    while y != 0:
        (x, y) = (y, x % y)
    return x

gcd(12,80)

4

In [ ]:
n=15
if n%3==0:
  print("fizz",end='')
if n%5==0:
  print("buzz",end='')

  

fizzbuzz

In [ ]:
nterms = 50
# first two terms
n1, n2 = 1, 1
count = 0
list_fib=[]
while count < nterms:
    
    list_fib.append(n1)
    nth = n1 + n2
    # update values
    n1 = n2
    n2 = nth
    count += 1
print(list_fib)   

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025]


**Functions Assingment**

In [ ]:
def is_prime(num):
  if num > 1: 
      
   # Iterate from 2 to n / 2  
   for i in range(2, num): 
         
       # If num is divisible by any number between  
       # 2 and n / 2, it is not prime  
       if (num % i) == 0: 
           Return False
           break
   else: 
       return True
  
  else: 
   return True
    
is_prime(13)

13 is a prime number


In [ ]:
def unique(list):
  unique_list=[]
  unique_list.append(list[0])
  for x in list:
    if x in unique_list:
      continue
    else: 
      unique_list.append(x)  
  print(unique_list)
     
unique([1,2,2,3,3,4,4])  


[1, 2, 3, 4]


In [ ]:
from datetime import date 
  
def calculateAge(birthDate): 
    today = date.today() 
    age = today.year - birthDate.year - ((today.month, today.day) < (birthDate.month, birthDate.day)) 
  
    return age 
      
# Driver code  
print(calculateAge(date(1998, 7, 18)), "years old")

22 years old


In [ ]:
def factorial(n):
  fact=1
  for i in range(1,n+1):
    fact*=i
  return fact

factorial(4)

24

In [ ]:
def perfect(number):
  Sum = 0
  for i in range(1, number):
      if(number % i == 0):
          Sum = Sum + i
  if (Sum == number):
      print(" %d is a Perfect Number" %number)
  else:
      print(" %d is not a Perfect Number" %number)
perfect(6)

 6 is a Perfect Number


In [ ]:
n=int(input("Enter number of rows: "))
a=[]
for i in range(n):
    a.append([])
    a[i].append(1)
    for j in range(1,i):
        a[i].append(a[i-1][j-1]+a[i-1][j])
    if(n!=0):
        a[i].append(1)
for i in range(n):
    print("   "*(n-i),end=" ",sep=" ")
    for j in range(0,i+1):
        print('{0:6}'.format(a[i][j]),end=" ",sep=" ")
    print()

Enter number of rows: 4
                  1 
               1      1 
            1      2      1 
         1      3      3      1 


**Classes Assingment**

In [ ]:
class item:
  def __init__(self, item_name,price):
        self.item_name = item_name
        self.price= price
class customer:
  def __init__(self,customer_id, phone_number):
        self.customer_id = customer_id
        self.phone_number=phone_number    
  def purchase(item_name,count,price):
    print(price*count)
    

In [ ]:
def main():
  items=item('item',120)
  custom=customer(1,534)
  custom.purchase(items.price,2)    
if __name__=='__main__':
    main()

240


**Errors Exception Handling**

In [ ]:
def handling(x):
  try:
    x=1/0
    
  except Exception as e:
    print ("'{}' error occurred! ".format(e))
handling(10)    

'division by zero' error occurred! 


In [ ]:
def name_error():
    try:
      print(hello)
    except NameError as err:
      print("Name is not defined")
name_error()

Name is not defined


In [ ]:
def handle_error_by_returning_none(input_data):
    try:
        return int(input_data)
    
    except ValueError:
        print('Wrong data type') 
handle_error_by_returning_none('Adam')

Wrong data type


**File Operations**

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')
import os
os.chdir("/content/drive/My Drive/Colab Notebooks")


with open("poem.txt", "r", encoding='utf8') as f:
    line=f.readline()
    rest_of_lines=f.readlines()
    
print(rest_of_lines)

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
['Where giant reddish-purple cauliflowers\n', '& white ones in French & English are outside\n', 'Waiting to welcome you to a boat\n', 'Over the low black river for a big dinner\n', "There's alot of choice among the foods\n", 'Even a tortured lamb']


**Python Data Sceince Libraries**

In [ ]:
import numpy as np

In [ ]:
house_size= list(range(100,300,20))
rooms = list(range(1,11,1))
price=list(range(10000,50000,4000))

size_arr=np.array(house_size)
rooms_arr=np.array(rooms)
price_arr=np.array(size_arr)

all=np.array([size_arr, rooms, price])
print(all)

[[  100   120   140   160   180   200   220   240   260   280]
 [    1     2     3     4     5     6     7     8     9    10]
 [10000 14000 18000 22000 26000 30000 34000 38000 42000 46000]]


In [ ]:
t_all=all.T
print(t_all)

[[  100     1 10000]
 [  120     2 14000]
 [  140     3 18000]
 [  160     4 22000]
 [  180     5 26000]
 [  200     6 30000]
 [  220     7 34000]
 [  240     8 38000]
 [  260     9 42000]
 [  280    10 46000]]


shape function display size of array

In [ ]:
t_all.shape

(10, 3)

In [ ]:
arr=np.ones((6,5))
for i in range(6):
  for j in range(5):
    if i%2==1 and j%2==1:
      arr[i][j]=0
print(arr)      

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]


**Indexing And Slicing Of Numpy Arrays Assingment**

In [ ]:
import pandas as pd
mydata= pd.read_csv("Earthquakes.csv")

In [ ]:
data_arr=np.array(mydata)
data_arr=data_arr[0:20,[ 3, 5, 6, 7, 12]]
data_arr

array([[ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28.1495,  6.25  ,  4.1   ],
       [ 0.    , 37.6883, 37

In [ ]:
np.where(data_arr[:,-1]>=4.5)

(array([ 3,  5,  6,  9, 10, 13, 14, 15]),)

In [ ]:
row[0]=1
print(row)

[[1. ]
 [4.4]
 [4. ]
 [4.5]
 [4.1]
 [5.2]
 [4.8]
 [4.3]
 [4.2]
 [4.8]
 [4.9]
 [4.3]
 [4.1]
 [4.5]
 [4.6]
 [4.5]
 [4.1]
 [4.1]
 [4.1]
 [4. ]]


**Mathematical Operations Numpy Array**

In [ ]:
np.mean(data_arr,axis=0)

array([ 0.      , 37.471645, 33.184785, 19.26    ,  4.38    ])

In [ ]:
np.std(data_arr,axis=0)

array([ 0.        ,  1.4170855 ,  5.91839567, 18.53566724,  0.33105891])

In [ ]:
data_arr.shape

(20, 5)

In [ ]:
data_arr2=data_arr*2